# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: collector.spec

# add or remove files that should be synced
files_to_sync:
    - collector.spec.in
    - .packit.yaml
    - Makefile
    - _build

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: red-hat-build-of-opentelemetry-collector
# downstream (Fedora) RPM package name
downstream_package_name: red-hat-build-of-opentelemetry-collector

actions:
  post-upstream-clone:
    - make collector.spec

  create-archive:
    - make archive

  get-current-version:
    - make version

jobs:
  - job: copr_build
    trigger: pull_request
    enable_net: True
    targets:
      - fedora-40-x86_64
      # - fedora-40-aarch64
      # - rhel-9-x86_64
      # - rhel-9-aarch64

  - job: tests
    trigger: pull_request
    targets:
      - fedora-40-x86_64
      # - fedora-40-aarch64
      # - rhel-9-x86_64
      # - rhel-9-aarch64

srpm_build_deps:
  - make
  - golang
  - git
